<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
     <PackageReference Include="Aspire.Hosting.Testing" />
     <PackageReference Include="coverlet.collector" />
     <PackageReference Include="HotChocolate.AspNetCore" />
     <PackageReference Include="Microsoft.NET.Test.Sdk" />
     <PackageReference Include="xunit" />
     <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ChrisClaude.AppHost\ChrisClaude.AppHost.csproj" />
    <ProjectReference Include="../../BlogAPI/BlogAPI.csproj" />
    <ProjectReference Include="../../Application/Application.csproj" />
    <ProjectReference Include="..\..\ChrisClaude.ServiceDefaults\ChrisClaude.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Aspire.Hosting.Testing" />
  </ItemGroup>

</Project>
