/* tslint:disable */
/* eslint-disable */
/**
 * BlogAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppError
 */
export interface AppError {
    /**
     * 
     * @type {string}
     * @memberof AppError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AppError
     */
    description: string;
}

/**
 * Check if a given object implements the AppError interface.
 */
export function instanceOfAppError(value: object): value is AppError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function AppErrorFromJSON(json: any): AppError {
    return AppErrorFromJSONTyped(json, false);
}

export function AppErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function AppErrorToJSON(json: any): AppError {
    return AppErrorToJSONTyped(json, false);
}

export function AppErrorToJSONTyped(value?: AppError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

