/* tslint:disable */
/* eslint-disable */
/**
 * BlogAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDto } from './PostDto';
import {
    PostDtoFromJSON,
    PostDtoFromJSONTyped,
    PostDtoToJSON,
    PostDtoToJSONTyped,
} from './PostDto';

/**
 * 
 * @export
 * @interface BookmarkDto
 */
export interface BookmarkDto {
    /**
     * 
     * @type {string}
     * @memberof BookmarkDto
     */
    postId: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkDto
     */
    userId?: string;
    /**
     * 
     * @type {PostDto}
     * @memberof BookmarkDto
     */
    post?: PostDto | null;
}

/**
 * Check if a given object implements the BookmarkDto interface.
 */
export function instanceOfBookmarkDto(value: object): value is BookmarkDto {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    return true;
}

export function BookmarkDtoFromJSON(json: any): BookmarkDto {
    return BookmarkDtoFromJSONTyped(json, false);
}

export function BookmarkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkDto {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'post': json['post'] == null ? undefined : PostDtoFromJSON(json['post']),
    };
}

export function BookmarkDtoToJSON(json: any): BookmarkDto {
    return BookmarkDtoToJSONTyped(json, false);
}

export function BookmarkDtoToJSONTyped(value?: BookmarkDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': value['postId'],
        'userId': value['userId'],
        'post': PostDtoToJSON(value['post']),
    };
}

