/* tslint:disable */
/* eslint-disable */
/**
 * BlogAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentDto
 */
export interface CommentDto {
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    postId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    authorId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CommentDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommentDto
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the CommentDto interface.
 */
export function instanceOfCommentDto(value: object): value is CommentDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CommentDtoFromJSON(json: any): CommentDto {
    return CommentDtoFromJSONTyped(json, false);
}

export function CommentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'postId': json['postId'] == null ? undefined : json['postId'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function CommentDtoToJSON(json: any): CommentDto {
    return CommentDtoToJSONTyped(json, false);
}

export function CommentDtoToJSONTyped(value?: CommentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'postId': value['postId'],
        'authorId': value['authorId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

