/* tslint:disable */
/* eslint-disable */
/**
 * BlogAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDto2 } from './PostDto2';
import {
    PostDto2FromJSON,
    PostDto2FromJSONTyped,
    PostDto2ToJSON,
    PostDto2ToJSONTyped,
} from './PostDto2';

/**
 * 
 * @export
 * @interface PostReactionDto
 */
export interface PostReactionDto {
    /**
     * 
     * @type {string}
     * @memberof PostReactionDto
     */
    postId: string;
    /**
     * 
     * @type {PostDto2}
     * @memberof PostReactionDto
     */
    post: PostDto2;
}

/**
 * Check if a given object implements the PostReactionDto interface.
 */
export function instanceOfPostReactionDto(value: object): value is PostReactionDto {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('post' in value) || value['post'] === undefined) return false;
    return true;
}

export function PostReactionDtoFromJSON(json: any): PostReactionDto {
    return PostReactionDtoFromJSONTyped(json, false);
}

export function PostReactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostReactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'post': PostDto2FromJSON(json['post']),
    };
}

export function PostReactionDtoToJSON(json: any): PostReactionDto {
    return PostReactionDtoToJSONTyped(json, false);
}

export function PostReactionDtoToJSONTyped(value?: PostReactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': value['postId'],
        'post': PostDto2ToJSON(value['post']),
    };
}

