/* tslint:disable */
/* eslint-disable */
/**
 * BlogAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostDto
 */
export interface PostDto {
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    excerpt: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    thumbnail: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    slug: string;
    /**
     * 
     * @type {number}
     * @memberof PostDto
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    authorId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PostDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PostDto
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the PostDto interface.
 */
export function instanceOfPostDto(value: object): value is PostDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('excerpt' in value) || value['excerpt'] === undefined) return false;
    if (!('thumbnail' in value) || value['thumbnail'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function PostDtoFromJSON(json: any): PostDto {
    return PostDtoFromJSONTyped(json, false);
}

export function PostDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'excerpt': json['excerpt'],
        'thumbnail': json['thumbnail'],
        'slug': json['slug'],
        'status': json['status'] == null ? undefined : json['status'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PostDtoToJSON(json: any): PostDto {
    return PostDtoToJSONTyped(json, false);
}

export function PostDtoToJSONTyped(value?: PostDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'excerpt': value['excerpt'],
        'thumbnail': value['thumbnail'],
        'slug': value['slug'],
        'status': value['status'],
        'authorId': value['authorId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

