/* tslint:disable */
/* eslint-disable */
/**
 * BlogAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleDto } from './RoleDto';
import {
    RoleDtoFromJSON,
    RoleDtoFromJSONTyped,
    RoleDtoToJSON,
    RoleDtoToJSONTyped,
} from './RoleDto';

/**
 * 
 * @export
 * @interface UserRoleDto
 */
export interface UserRoleDto {
    /**
     * 
     * @type {RoleDto}
     * @memberof UserRoleDto
     */
    role: RoleDto;
}

/**
 * Check if a given object implements the UserRoleDto interface.
 */
export function instanceOfUserRoleDto(value: object): value is UserRoleDto {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserRoleDtoFromJSON(json: any): UserRoleDto {
    return UserRoleDtoFromJSONTyped(json, false);
}

export function UserRoleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'role': RoleDtoFromJSON(json['role']),
    };
}

export function UserRoleDtoToJSON(json: any): UserRoleDto {
    return UserRoleDtoToJSONTyped(json, false);
}

export function UserRoleDtoToJSONTyped(value?: UserRoleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': RoleDtoToJSON(value['role']),
    };
}

