/* tslint:disable */
/* eslint-disable */
/**
 * BlogAPI | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDto2 } from './PostDto2';
import {
    PostDto2FromJSON,
    PostDto2FromJSONTyped,
    PostDto2ToJSON,
    PostDto2ToJSONTyped,
} from './PostDto2';
import type { UserRoleDto } from './UserRoleDto';
import {
    UserRoleDtoFromJSON,
    UserRoleDtoFromJSONTyped,
    UserRoleDtoToJSON,
    UserRoleDtoToJSONTyped,
} from './UserRoleDto';
import type { BookmarkDto } from './BookmarkDto';
import {
    BookmarkDtoFromJSON,
    BookmarkDtoFromJSONTyped,
    BookmarkDtoToJSON,
    BookmarkDtoToJSONTyped,
} from './BookmarkDto';
import type { PostReactionDto } from './PostReactionDto';
import {
    PostReactionDtoFromJSON,
    PostReactionDtoFromJSONTyped,
    PostReactionDtoToJSON,
    PostReactionDtoToJSONTyped,
} from './PostReactionDto';
import type { CommentDto } from './CommentDto';
import {
    CommentDtoFromJSON,
    CommentDtoFromJSONTyped,
    CommentDtoToJSON,
    CommentDtoToJSONTyped,
} from './CommentDto';

/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    surname: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    image?: string | null;
    /**
     * 
     * @type {Array<UserRoleDto>}
     * @memberof UserDto
     */
    userRoles: Array<UserRoleDto>;
    /**
     * 
     * @type {Array<BookmarkDto>}
     * @memberof UserDto
     */
    bookmarks?: Array<BookmarkDto> | null;
    /**
     * 
     * @type {Array<PostReactionDto>}
     * @memberof UserDto
     */
    postReactions?: Array<PostReactionDto> | null;
    /**
     * 
     * @type {Array<CommentDto>}
     * @memberof UserDto
     */
    comments?: Array<CommentDto> | null;
    /**
     * 
     * @type {Array<PostDto2>}
     * @memberof UserDto
     */
    posts?: Array<PostDto2> | null;
}

/**
 * Check if a given object implements the UserDto interface.
 */
export function instanceOfUserDto(value: object): value is UserDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('surname' in value) || value['surname'] === undefined) return false;
    if (!('userRoles' in value) || value['userRoles'] === undefined) return false;
    return true;
}

export function UserDtoFromJSON(json: any): UserDto {
    return UserDtoFromJSONTyped(json, false);
}

export function UserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'],
        'name': json['name'],
        'surname': json['surname'],
        'image': json['image'] == null ? undefined : json['image'],
        'userRoles': ((json['userRoles'] as Array<any>).map(UserRoleDtoFromJSON)),
        'bookmarks': json['bookmarks'] == null ? undefined : ((json['bookmarks'] as Array<any>).map(BookmarkDtoFromJSON)),
        'postReactions': json['postReactions'] == null ? undefined : ((json['postReactions'] as Array<any>).map(PostReactionDtoFromJSON)),
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(CommentDtoFromJSON)),
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(PostDto2FromJSON)),
    };
}

export function UserDtoToJSON(json: any): UserDto {
    return UserDtoToJSONTyped(json, false);
}

export function UserDtoToJSONTyped(value?: UserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
        'surname': value['surname'],
        'image': value['image'],
        'userRoles': ((value['userRoles'] as Array<any>).map(UserRoleDtoToJSON)),
        'bookmarks': value['bookmarks'] == null ? undefined : ((value['bookmarks'] as Array<any>).map(BookmarkDtoToJSON)),
        'postReactions': value['postReactions'] == null ? undefined : ((value['postReactions'] as Array<any>).map(PostReactionDtoToJSON)),
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(CommentDtoToJSON)),
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(PostDto2ToJSON)),
    };
}

