/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation AddBookmark($input: AddBookmarkInput!) {\n    addBookmark(input: $input) {\n      bookmarkDto {\n        postId\n        userId\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": typeof types.AddBookmarkDocument,
    "\n  mutation RemoveBookmark($input: RemoveBookmarkInput!) {\n    removeBookmark(input: $input) {\n      bookmarkDto {\n        postId\n        userId\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": typeof types.RemoveBookmarkDocument,
    "\n  mutation UpdatePost($input: UpdatePostInput!) {\n    updatePost(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        createdAt\n        updatedAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": typeof types.UpdatePostDocument,
    "\n  mutation AdminUpdatePostStatus($input: AdminUpdatePostStatusInput!) {\n    adminUpdatePostStatus(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        status\n        updatedAt\n        author {\n          id\n          name\n          surname\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": typeof types.AdminUpdatePostStatusDocument,
    "\n  mutation CreatePost($input: CreatePostInput!) {\n    createPost(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": typeof types.CreatePostDocument,
    "\n  mutation CreateTag($input: CreateTagInput!) {\n    createTag(input: $input) {\n      tagDto {\n        id\n        name\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": typeof types.CreateTagDocument,
    "\n  mutation RequestImageUploadUrl($input: RequestImageUploadUrlInput!) {\n    requestImageUploadUrl(input: $input) {\n      imageUploadToken {\n        uploadUrl\n        blobUrl\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n      }\n    }\n  }\n": typeof types.RequestImageUploadUrlDocument,
    "\n  mutation AdminUpdateUser($input: AdminUpdateUserInput!) {\n    adminUpdateUser(input: $input) {\n      userDto {\n        id\n        name\n        surname\n        image\n        email\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": typeof types.AdminUpdateUserDocument,
    "\n  mutation AdminUpdateUserRoles($input: AdminUpdateUserRolesInput!) {\n    adminUpdateUserRoles(input: $input) {\n      userDto {\n        id\n        email\n        name\n        surname\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": typeof types.AdminUpdateUserRolesDocument,
    "\n  mutation UpdateUser($input: UpdateUserInput!) {\n    updateUser(input: $input) {\n      userDto {\n        id\n        name\n        surname\n        image\n        email\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": typeof types.UpdateUserDocument,
    "\n  query GetMyBookmarks {\n    myBookmarks {\n      postId\n      userId\n      post {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        publishedAt\n        createdAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n        author {\n          id\n          name\n          surname\n          image\n        }\n      }\n    }\n  }\n": typeof types.GetMyBookmarksDocument,
    "\n  query GetMyPosts($first: Int, $after: String) {\n    myPosts(first: $first, after: $after, order: { createdAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        updatedAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetMyPostsDocument,
    "\n  query GetAllPostsAdmin($first: Int, $after: String) {\n    allPostsAdmin(first: $first, after: $after, order: { createdAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        updatedAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetAllPostsAdminDocument,
    "\n  query GetPosts($first: Int, $after: String) {\n    posts(first: $first, after: $after, order: { publishedAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetPostsDocument,
    "\n  query GetPostBySlug($slug: String!) {\n    posts(first: 1, where: { slug: { eq: $slug } }) {\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        content\n        status\n        publishedAt\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetPostBySlugDocument,
    "\n  query SearchTags($first: Int, $search: String) {\n    tags(\n      first: $first\n      where: { name: { contains: $search } }\n      order: { name: ASC }\n    ) {\n      nodes {\n        id\n        name\n      }\n    }\n  }\n": typeof types.SearchTagsDocument,
    "\n  query GetAllTags($first: Int, $after: String) {\n    tags(first: $first, after: $after, order: { name: ASC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      nodes {\n        id\n        name\n        createdAt\n      }\n    }\n  }\n": typeof types.GetAllTagsDocument,
    "\n  query GetMe {\n    me {\n      id\n      email\n      name\n      surname\n      image\n      userRoles {\n        role {\n          name\n        }\n      }\n    }\n  }\n": typeof types.GetMeDocument,
    "\n  query GetUsers($first: Int, $after: String) {\n    users(first: $first, after: $after) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        email\n        name\n        surname\n        image\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetUsersDocument,
};
const documents: Documents = {
    "\n  mutation AddBookmark($input: AddBookmarkInput!) {\n    addBookmark(input: $input) {\n      bookmarkDto {\n        postId\n        userId\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": types.AddBookmarkDocument,
    "\n  mutation RemoveBookmark($input: RemoveBookmarkInput!) {\n    removeBookmark(input: $input) {\n      bookmarkDto {\n        postId\n        userId\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": types.RemoveBookmarkDocument,
    "\n  mutation UpdatePost($input: UpdatePostInput!) {\n    updatePost(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        createdAt\n        updatedAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": types.UpdatePostDocument,
    "\n  mutation AdminUpdatePostStatus($input: AdminUpdatePostStatusInput!) {\n    adminUpdatePostStatus(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        status\n        updatedAt\n        author {\n          id\n          name\n          surname\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": types.AdminUpdatePostStatusDocument,
    "\n  mutation CreatePost($input: CreatePostInput!) {\n    createPost(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": types.CreatePostDocument,
    "\n  mutation CreateTag($input: CreateTagInput!) {\n    createTag(input: $input) {\n      tagDto {\n        id\n        name\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": types.CreateTagDocument,
    "\n  mutation RequestImageUploadUrl($input: RequestImageUploadUrlInput!) {\n    requestImageUploadUrl(input: $input) {\n      imageUploadToken {\n        uploadUrl\n        blobUrl\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n      }\n    }\n  }\n": types.RequestImageUploadUrlDocument,
    "\n  mutation AdminUpdateUser($input: AdminUpdateUserInput!) {\n    adminUpdateUser(input: $input) {\n      userDto {\n        id\n        name\n        surname\n        image\n        email\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": types.AdminUpdateUserDocument,
    "\n  mutation AdminUpdateUserRoles($input: AdminUpdateUserRolesInput!) {\n    adminUpdateUserRoles(input: $input) {\n      userDto {\n        id\n        email\n        name\n        surname\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": types.AdminUpdateUserRolesDocument,
    "\n  mutation UpdateUser($input: UpdateUserInput!) {\n    updateUser(input: $input) {\n      userDto {\n        id\n        name\n        surname\n        image\n        email\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n": types.UpdateUserDocument,
    "\n  query GetMyBookmarks {\n    myBookmarks {\n      postId\n      userId\n      post {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        publishedAt\n        createdAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n        author {\n          id\n          name\n          surname\n          image\n        }\n      }\n    }\n  }\n": types.GetMyBookmarksDocument,
    "\n  query GetMyPosts($first: Int, $after: String) {\n    myPosts(first: $first, after: $after, order: { createdAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        updatedAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetMyPostsDocument,
    "\n  query GetAllPostsAdmin($first: Int, $after: String) {\n    allPostsAdmin(first: $first, after: $after, order: { createdAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        updatedAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetAllPostsAdminDocument,
    "\n  query GetPosts($first: Int, $after: String) {\n    posts(first: $first, after: $after, order: { publishedAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetPostsDocument,
    "\n  query GetPostBySlug($slug: String!) {\n    posts(first: 1, where: { slug: { eq: $slug } }) {\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        content\n        status\n        publishedAt\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetPostBySlugDocument,
    "\n  query SearchTags($first: Int, $search: String) {\n    tags(\n      first: $first\n      where: { name: { contains: $search } }\n      order: { name: ASC }\n    ) {\n      nodes {\n        id\n        name\n      }\n    }\n  }\n": types.SearchTagsDocument,
    "\n  query GetAllTags($first: Int, $after: String) {\n    tags(first: $first, after: $after, order: { name: ASC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      nodes {\n        id\n        name\n        createdAt\n      }\n    }\n  }\n": types.GetAllTagsDocument,
    "\n  query GetMe {\n    me {\n      id\n      email\n      name\n      surname\n      image\n      userRoles {\n        role {\n          name\n        }\n      }\n    }\n  }\n": types.GetMeDocument,
    "\n  query GetUsers($first: Int, $after: String) {\n    users(first: $first, after: $after) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        email\n        name\n        surname\n        image\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetUsersDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation AddBookmark($input: AddBookmarkInput!) {\n    addBookmark(input: $input) {\n      bookmarkDto {\n        postId\n        userId\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AddBookmark($input: AddBookmarkInput!) {\n    addBookmark(input: $input) {\n      bookmarkDto {\n        postId\n        userId\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation RemoveBookmark($input: RemoveBookmarkInput!) {\n    removeBookmark(input: $input) {\n      bookmarkDto {\n        postId\n        userId\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation RemoveBookmark($input: RemoveBookmarkInput!) {\n    removeBookmark(input: $input) {\n      bookmarkDto {\n        postId\n        userId\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdatePost($input: UpdatePostInput!) {\n    updatePost(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        createdAt\n        updatedAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdatePost($input: UpdatePostInput!) {\n    updatePost(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        createdAt\n        updatedAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation AdminUpdatePostStatus($input: AdminUpdatePostStatusInput!) {\n    adminUpdatePostStatus(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        status\n        updatedAt\n        author {\n          id\n          name\n          surname\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AdminUpdatePostStatus($input: AdminUpdatePostStatusInput!) {\n    adminUpdatePostStatus(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        status\n        updatedAt\n        author {\n          id\n          name\n          surname\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreatePost($input: CreatePostInput!) {\n    createPost(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreatePost($input: CreatePostInput!) {\n    createPost(input: $input) {\n      postDto {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateTag($input: CreateTagInput!) {\n    createTag(input: $input) {\n      tagDto {\n        id\n        name\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateTag($input: CreateTagInput!) {\n    createTag(input: $input) {\n      tagDto {\n        id\n        name\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation RequestImageUploadUrl($input: RequestImageUploadUrlInput!) {\n    requestImageUploadUrl(input: $input) {\n      imageUploadToken {\n        uploadUrl\n        blobUrl\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation RequestImageUploadUrl($input: RequestImageUploadUrlInput!) {\n    requestImageUploadUrl(input: $input) {\n      imageUploadToken {\n        uploadUrl\n        blobUrl\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation AdminUpdateUser($input: AdminUpdateUserInput!) {\n    adminUpdateUser(input: $input) {\n      userDto {\n        id\n        name\n        surname\n        image\n        email\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AdminUpdateUser($input: AdminUpdateUserInput!) {\n    adminUpdateUser(input: $input) {\n      userDto {\n        id\n        name\n        surname\n        image\n        email\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation AdminUpdateUserRoles($input: AdminUpdateUserRolesInput!) {\n    adminUpdateUserRoles(input: $input) {\n      userDto {\n        id\n        email\n        name\n        surname\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AdminUpdateUserRoles($input: AdminUpdateUserRolesInput!) {\n    adminUpdateUserRoles(input: $input) {\n      userDto {\n        id\n        email\n        name\n        surname\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateUser($input: UpdateUserInput!) {\n    updateUser(input: $input) {\n      userDto {\n        id\n        name\n        surname\n        image\n        email\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateUser($input: UpdateUserInput!) {\n    updateUser(input: $input) {\n      userDto {\n        id\n        name\n        surname\n        image\n        email\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n      errors {\n        ... on UserContextError {\n          message\n        }\n        ... on DomainError {\n          message\n          code\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMyBookmarks {\n    myBookmarks {\n      postId\n      userId\n      post {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        publishedAt\n        createdAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n        author {\n          id\n          name\n          surname\n          image\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMyBookmarks {\n    myBookmarks {\n      postId\n      userId\n      post {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        publishedAt\n        createdAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n        author {\n          id\n          name\n          surname\n          image\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMyPosts($first: Int, $after: String) {\n    myPosts(first: $first, after: $after, order: { createdAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        updatedAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMyPosts($first: Int, $after: String) {\n    myPosts(first: $first, after: $after, order: { createdAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        updatedAt\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetAllPostsAdmin($first: Int, $after: String) {\n    allPostsAdmin(first: $first, after: $after, order: { createdAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        updatedAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetAllPostsAdmin($first: Int, $after: String) {\n    allPostsAdmin(first: $first, after: $after, order: { createdAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        updatedAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetPosts($first: Int, $after: String) {\n    posts(first: $first, after: $after, order: { publishedAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPosts($first: Int, $after: String) {\n    posts(first: $first, after: $after, order: { publishedAt: DESC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        status\n        publishedAt\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetPostBySlug($slug: String!) {\n    posts(first: 1, where: { slug: { eq: $slug } }) {\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        content\n        status\n        publishedAt\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPostBySlug($slug: String!) {\n    posts(first: 1, where: { slug: { eq: $slug } }) {\n      nodes {\n        id\n        title\n        slug\n        excerpt\n        thumbnail\n        content\n        status\n        publishedAt\n        createdAt\n        author {\n          id\n          name\n          surname\n          image\n        }\n        postTags {\n          tag {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query SearchTags($first: Int, $search: String) {\n    tags(\n      first: $first\n      where: { name: { contains: $search } }\n      order: { name: ASC }\n    ) {\n      nodes {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query SearchTags($first: Int, $search: String) {\n    tags(\n      first: $first\n      where: { name: { contains: $search } }\n      order: { name: ASC }\n    ) {\n      nodes {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetAllTags($first: Int, $after: String) {\n    tags(first: $first, after: $after, order: { name: ASC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      nodes {\n        id\n        name\n        createdAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetAllTags($first: Int, $after: String) {\n    tags(first: $first, after: $after, order: { name: ASC }) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      nodes {\n        id\n        name\n        createdAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMe {\n    me {\n      id\n      email\n      name\n      surname\n      image\n      userRoles {\n        role {\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMe {\n    me {\n      id\n      email\n      name\n      surname\n      image\n      userRoles {\n        role {\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetUsers($first: Int, $after: String) {\n    users(first: $first, after: $after) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        email\n        name\n        surname\n        image\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetUsers($first: Int, $after: String) {\n    users(first: $first, after: $after) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      nodes {\n        id\n        email\n        name\n        surname\n        image\n        userRoles {\n          role {\n            name\n          }\n        }\n      }\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;